Numpy


In [1]:
import numpy as np

create 1D array using numpy


In [2]:
arr1=np.array([1,2,3])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


converting it to 2D

In [3]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) 
# 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

Make 2D directly

In [4]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


create arrays with some in built functions

In [8]:
np.arange(0,10,2)



array([0, 2, 4, 6, 8])

In [9]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

attributes of numpy array

In [12]:
arr2=np.array([[1,2,3],[4,5,6]])
print("array",arr2)
print("shape",arr2.shape)
print("number of dimensions",arr2.ndim)
print("size",arr2.size)
print("data type",arr2.dtype)
print("item size in bytes",arr2.itemsize)


array [[1 2 3]
 [4 5 6]]
shape (2, 3)
number of dimensions 2
size 6
data type int32
item size in bytes 4


Vectorized operations on Numpy

In [13]:
arr1 = np.array([1, 2, 3,4,5])
arr2 = np.array([6, 7, 8,9,10])


In [15]:
# element-wise addition
arr3 = arr1 + arr2
print("arr1 + arr2 = ", arr3)
# similarly for subtraction, multiplication and division
arr4 = arr1 - arr2      
print("arr1 - arr2 = ", arr4)
arr5 = arr1 * arr2
print("arr1 * arr2 = ", arr5)

arr1 + arr2 =  [ 7  9 11 13 15]
arr1 - arr2 =  [-5 -5 -5 -5 -5]
arr1 * arr2 =  [ 6 14 24 36 50]


In [16]:
# universal functions
arr = np.array([1, 2, 3, 4])
# sqrt
print("sqrt(arr) = ", np.sqrt(arr))
# exponential
print("exp(arr) = ", np.exp(arr))
# sine
print("sin(arr) = ", np.sin(arr))
# logarithm
print("log(arr) = ", np.log(arr))

sqrt(arr) =  [1.         1.41421356 1.73205081 2.        ]
exp(arr) =  [ 2.71828183  7.3890561  20.08553692 54.59815003]
sin(arr) =  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
log(arr) =  [0.         0.69314718 1.09861229 1.38629436]
